import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Sidebar } from '@/components/layout/Sidebar'
import { FollowBar } from '@/components/layout/FollowBar'
import { LoginModal } from '@/components/models/LoginModal'
import { RegisterModal } from '@/components/models/RegisterModal'
import { Toaster } from 'react-hot-toast'
import { SessionProvider } from 'next-auth/react'
import ClientSessionProvider from '@/components/ClientSessionProvider'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import { getServerSession } from 'next-auth'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}

export default async function RootLayout({
   children,
}: Readonly<{ children: React.ReactNode }>) {
   const session = await getServerSession(authOptions)

   return (
      <html lang="en">
         <body className={inter.className}>
            {/* Proveedor de la sesión de NextAuth */}
            <ClientSessionProvider session={session}>
               {/* Modales de autenticación */}
               <LoginModal />
               <RegisterModal />

               {/* Notificaciones */}
               <Toaster />

               {/* Layout principal */}
               <div className="h-screen bg-black">
                  <div className="container h-full mx-auto xl:px-30 max-w-6xl">
                     <div className="grid grid-cols-4 h-full">
                        <Sidebar />

                        {/* Contenido principal */}
                        <div
                           className="
                           col-span-3 
                           lg:col-span-2 
                           border-x-[1px] 
                           border-neutral-800"
                        >
                           {children}
                        </div>

                        {/* Barra lateral de seguimiento */}
                        <FollowBar />
                     </div>
                  </div>
               </div>
            </ClientSessionProvider>
         </body>
      </html>
   )
}
